title: Alex Manson # name of the site
author: Alex Manson # name of site's author
email: dev@neurowinter.com # email of site's author
baseurl: ""  # Weird issue here if this was not set then `pages/Neurowinter` was added to the css url
url: https://neurowinter.com # root address of the site
description: > # description of the site (multiple lines allowed)
  Security researcher and SRE. Writing about vulnerability research, AI, and the practical stuff I figure out along the way.
permalink: pretty
repository: NeuroWinter/neurowinter.github.io
timezone: Pacific/Auckland

favicon: "./logo.png" # relative path to site's favicon
goat_counter: "neurowinter" # put your GoatCounter name if you want to use GoatCounter analytics

# Here are a bunch of SEO things
icon: "./logo.png" # relative path to site's favicon

twitter:
  username: NeuroWinter
  card: summary

social:
  name: Alex Manson
  links:
    - https://twitter.com/NeuroWinter
    - https://tilde.zone/@NeuroWinter
    - https://www.linkedin.com/in/alex-manson/
    - https://bsky.app/profile/neurowinter.bsky.social

google_site_verification: Cg3NHpLRBqjYq_ZQHk1IJSEAiWLub7eZ-V4E5lkacxE
google_analytics: G-6DKEYWKCBN

remote_theme: NeuroWinter/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
